### ISSUE TITLE
导出漏洞报告有问题

### ISSUE THREAD

**Issue by Wwon1oung** [0x727/BugRepoter_0x727#10]
1.点击导出漏洞报告，使用默认模版显示模版不存在。
![7452F225ADAF9175BCE77653B387286E](https://user-images.githubusercontent.com/55070231/150510286-2f0b9d97-5f06-409c-a6c0-9583a8b22f33.jpg)

点击导出复测报告跳转到空白页。

2.功能建议：模版列表添加是否能增加上传文件？复制粘贴时内容有时候格式会变

谢谢师傅

**Comment by xz-zone** [comment]
给文件权限。

**Comment by Wwon1oung** [comment]
是给了的。chmod 777 -R BugRepoter_0x727
![image](https://user-images.githubusercontent.com/55070231/150958452-82597e98-95c7-45a8-9445-363373a690e7.png)

**Comment by Wwon1oung** [comment]
需要验证

**Comment by xz-zone** [comment]
在加试下



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wwon1oung ***@***.***&gt;
发送时间: 2022年1月26日 10:36
收件人: 0x727/BugRepoter_0x727 ***@***.***&gt;
抄送: 小洲 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [0x727/BugRepoter_0x727] 导出漏洞报告有问题 (Issue #10)





 
需要验证
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xz-zone** [comment]
已修复该问题

**Comment by Wwon1oung** [comment]
师傅，有点问题，qq私信你了，新建模板会出错

**Comment by xz-zone** [comment]
加1047189056




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "0x727/BugRepoter_0x727"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月25日(星期五) 下午4:42
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [0x727/BugRepoter_0x727] 导出漏洞报告有问题 (Issue #10)





 
师傅，有点问题，qq私信你了，新建模板会出错
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
