### ISSUE TITLE
安装onlyoffice模块的问题

### ISSUE THREAD

**Issue by jinghunsanzu** [0x727/BugRepoter_0x727#12]
我已经使用docker安装onlyoffice模块但是还是提示我如下图片所示的样子，是否我执行的命令有误
![image](https://user-images.githubusercontent.com/54282451/175372185-b9c999eb-c93e-4bf8-a160-9c1ab8462e6a.png)

**Comment by jinghunsanzu** [comment]
我使用的是源码安装

**Comment by xz-zone** [comment]
> 我使用的是源码安装

报什么错

**Comment by jinghunsanzu** [comment]
按照图中的代码进行启动，重新刷新还是一样的爆出请安装onlyoffice模块
请问
docker exec $(docker ps -a | grep -E "(onlyoffice/documentserver)" | awk '{ print $1 }') rm -rf /var/www/onlyoffice/documentserver-example

docker exec $(docker ps -a | grep -E "(onlyoffice/documentserver)" | awk '{ print $1 }') /usr/sbin/nginx
这两句时什么意思呢

**Comment by xz-zone** [comment]
已解决 更新最新。

**Comment by xz-zone** [comment]
已解决 更新最新。
