### ISSUE TITLE
添加和编辑模板问题

### ISSUE THREAD

**Issue by nihou11** [0x727/BugRepoter_0x727#13]
添加和编辑模板报错

![微信图片_20220812153513](https://user-images.githubusercontent.com/111113703/184307201-61373cc4-5329-47a2-952a-e4dcde536d33.png)
![微信图片_20220812153517](https://user-images.githubusercontent.com/111113703/184307207-38c1ad8b-a940-4056-b526-9127ee0cec82.png)

**Comment by xz-zone** [comment]
查看下docker是否启动，并且查看下目录权限

**Comment by nihou11** [comment]
docker已启动，权限为77
![微信截图_20220812154252](https://user-images.githubusercontent.com/111113703/184308435-8f0ef56a-c7bc-4db4-b496-aca9f600d218.png)
![微信截图_20220812154240](https://user-images.githubusercontent.com/111113703/184308444-5cfc589a-872e-4bff-94ec-2608ef2a4e4b.png)
7

**Comment by xz-zone** [comment]
> docker已启动，权限为77 ![微信截图_20220812154252](https://user-images.githubusercontent.com/111113703/184308435-8f0ef56a-c7bc-4db4-b496-aca9f600d218.png) ![微信截图_20220812154240](https://user-images.githubusercontent.com/111113703/184308444-5cfc589a-872e-4bff-94ec-2608ef2a4e4b.png) 7

加1047189056 远程帮你看看

**Comment by nihou11** [comment]
已加

**Comment by xz-zone** [comment]
> 已加

还是有问题？

**Comment by nihou11** [comment]
没有了




***@***.***
 
发件人： 小洲
发送时间： 2022-10-08 14:02
收件人： 0x727/BugRepoter_0x727
抄送： nihou11; Author
主题： Re: [0x727/BugRepoter_0x727] 添加和编辑模板问题 (Issue #13)
已加
还是有问题？

**Comment by xz-zone** [comment]
已解决 更新最新。
