### ISSUE TITLE
安装报错

### ISSUE THREAD

**Issue by xxsmile123** [0x727/BugRepoter_0x727#14]
使用的版本
最新版

报错内容：
[root@mimikatz-pc docker]# docker-compose up --build -d && rm -rf ../html
Building mysql
Step 1/1 : FROM mysql:5.6.50
 ---> 6e68afc1976f
Successfully built 6e68afc1976f
Building python
Step 1/3 : FROM bugrepoter/python:1.0
 ---> e6c94c789a2a
Step 2/3 : ADD . /app
 ---> Using cache
 ---> e5fa2394422a
Step 3/3 : WORKDIR /app
 ---> Using cache
 ---> b480a49b4975
Successfully built b480a49b4975
Building php
Step 1/1 : FROM bugrepoter/php-7.3:1.0
 ---> 19b338a6fce0
Successfully built 19b338a6fce0
Building nginx
Step 1/1 : FROM nginx:1.18.0
 ---> c2c45d506085
Successfully built c2c45d506085
Building onlyoffice
Step 1/1 : FROM onlyoffice/documentserver
Trying to pull repository docker.io/onlyoffice/documentserver ...
latest: Pulling from docker.io/onlyoffice/documentserver
d5fd17ec1767: Pull complete
05cf01b35c53: Pull complete
603744b8c3ff: Pull complete
65a320ec6c4e: Pull complete
ae7fe860fb26: Pull complete
Digest: sha256:8a1edcc13f9d9dd61f3e77bcb172b0f32d0788aa2c63bb5a1206a7633e3dd2f8
Status: Downloaded newer image for docker.io/onlyoffice/documentserver:latest
 ---> 5a50e3a2d2ed
Successfully built 5a50e3a2d2ed
Creating docker_onlyoffice_1 ... done
Creating docker_mysql_1      ... done
Creating docker_python_1     ... done
Creating docker_php_1        ... error

ERROR: for docker_php_1  Cannot start service php: oci runtime error: container_linux.go:290: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: no such file or directory"

ERROR: for php  Cannot start service php: oci runtime error: container_linux.go:290: starting container process caused "chdir to cwd (\"/var/www/html\") set in config.json failed: no such file or directory"

ERROR: Encountered errors while bringing up the project.
[root@mimikatz-pc docker]#

**Comment by xxsmile123** [comment]
使用run_docker.sh中的命令安装。
测试平台：
[root@mimikatz-pc etc]# cat centos-release
CentOS Linux release 7.8.2003 (Core)

直接执行脚本有如下报错：
[root@mimikatz-pc docker]# bash run_docker.sh
：没有那个文件或目录fig/system.php
run_docker.sh:行19: 未预期的符号 `elif' 附近有语法错误
'un_docker.sh:行19: `elif grep -Eqi "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release; then

**Comment by xz-zone** [comment]
> 使用run_docker.sh中的命令安装。 测试平台： [root@mimikatz-pc etc]# cat centos-release CentOS Linux release 7.8.2003 (Core)
> 
> 直接执行脚本有如下报错： [root@mimikatz-pc docker]# bash run_docker.sh ：没有那个文件或目录fig/system.php run_docker.sh:行19: 未预期的符号 `elif' 附近有语法错误 'un_docker.sh:行19: `elif grep -Eqi "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release; then

好的，正在测试

**Comment by xz-zone** [comment]
> 使用run_docker.sh中的命令安装。 测试平台： [root@mimikatz-pc etc]# cat centos-release CentOS Linux release 7.8.2003 (Core)
> 
> 直接执行脚本有如下报错： [root@mimikatz-pc docker]# bash run_docker.sh ：没有那个文件或目录fig/system.php run_docker.sh:行19: 未预期的符号 `elif' 附近有语法错误 'un_docker.sh:行19: `elif grep -Eqi "Ubuntu" /etc/issue || grep -Eq "Ubuntu" /etc/*-release; then

已经更新脚本，本地测试没问题

**Comment by xxsmile123** [comment]
![image](https://user-images.githubusercontent.com/43473886/185964326-1dad69e2-2145-4873-811a-a727f9723995.png)
还是不太行。

**Comment by xxsmile123** [comment]
脚本运行还是报错，但是使用脚本中相关的安装命令是没问题的。
报错界面：
![image](https://user-images.githubusercontent.com/43473886/186041114-34282c99-e2f6-493f-8016-178a756f8677.png)
安装命令：
sed -i "s|127.0.0.1|192.168.5.103|" ../config/system.php
yum install wget yum-utils device-mapper-persistent-data lvm2 -y
docker-compose下载url：https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
chmod +x /usr/local/bin/docker-compose
ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
yum install docker-ce-17.12.0.ce -y
systemctl start docker
docker-compose up --build -d && rm -rf ../html
![image](https://user-images.githubusercontent.com/43473886/186041480-f1e334c2-eac1-4a87-aded-8376c99facb0.png)
![image](https://user-images.githubusercontent.com/43473886/186041538-cc81e099-e2fb-4837-b49b-8a8c64c8af22.png)
我觉得您应该修正一下docker-compose的下载url。

**Comment by xz-zone** [comment]
> 脚本运行还是报错，但是使用脚本中相关的安装命令是没问题的。
> 报错界面：

您是使用最新的项目吗
