### ISSUE TITLE
编辑/修改模板时出现问题，“文档安全令牌未正确形成”

### ISSUE THREAD

**Issue by heisefangkuai** [0x727/BugRepoter_0x727#16]
使用最新的docker安装方式搭建平台出现下面的报错
![image](https://user-images.githubusercontent.com/38220741/194304951-80c7eb3a-593e-4af3-84f8-62bbac9719dc.png)

onlyoffice_1  | ==> /var/log/onlyoffice/documentserver/docservice/out.log <==
onlyoffice_1  | [2022-10-06T11:45:55.587] [WARN] [localhost] [3436501423] [1] nodeJS - checkJwt error: name = JsonWebTokenError message = jwt must be provided token = undefined

**Comment by xz-zone** [comment]
删除onlyoffice docker重新部署

**Comment by xz-zone** [comment]
> 过了几分钟后onlyoffice又显示了文档安全令牌为正确形成 ![image](https://user-images.githubusercontent.com/38220741/194349145-97907f9a-e4a4-4fc0-916a-1b8a347093da.png)

你是用什么浏览器？

**Comment by heisefangkuai** [comment]
> > 过了几分钟后onlyoffice又显示了文档安全令牌为正确形成 ![image](https://user-images.githubusercontent.com/38220741/194349145-97907f9a-e4a4-4fc0-916a-1b8a347093da.png)
> 
> 你是用什么浏览器？

edge和火狐

**Comment by xz-zone** [comment]
> > > 过了几分钟后onlyoffice又显示了文档安全令牌为正确形成 ![image](https://user-images.githubusercontent.com/38220741/194349145-97907f9a-e4a4-4fc0-916a-1b8a347093da.png)
> > 
> > 
> > 你是用什么浏览器？
> 
> edge和火狐

能否远程

**Comment by PippyBear** [comment]
我这边也有这个问题，请问是怎么解决的？

**Comment by xz-zone** [comment]
已解决 更新最新。
