### ISSUE TITLE
疑似被植入后门

### ISSUE THREAD

**Issue by CrazyRobert** [0x727/BugRepoter_0x727#19]
系统依赖的图片实际是html文件，且包含调用访问恶意域名，疑似被植入后门。
https://github.com/0x727/BugRepoter_0x727/blob/main/public/index/vendor/datatables/sampleImage.jpg
![1673332120697](https://user-images.githubusercontent.com/6202489/211477790-91eb3f3b-8b82-42e5-b536-99026ab628b1.jpg)
文件被BugRepoter_0x727-main\public\index\vendor\datatables\vfs_fonts.js调用
![1673332243494](https://user-images.githubusercontent.com/6202489/211478083-89783f7a-3362-4f40-a23a-1224440725b7.png)
![240cdcc4099167b8276fccc89eb2fd8](https://user-images.githubusercontent.com/6202489/211479597-9197a2b3-9808-4d5f-b4dc-a4bc5678c5e5.png)

奇安信云沙箱识别
https://sandbox.ti.qianxin.com/sandbox/page/detail?type=file&id=AYWZ-q--a5r8Rybxc4gd&env=&time=&sha1=7e704e57162ed18743bef9f95e2dea558954751b
![a18e8c0f10841e1622fce0f3159f6c6](https://user-images.githubusercontent.com/6202489/211479230-18440b08-a920-46e4-9fac-b47b02e7c8c9.png)
![8bb0e13e448e85c45ba6fa4f3cd8011](https://user-images.githubusercontent.com/6202489/211479257-416c6bde-05de-402f-bf3d-c78f065fc44b.png)

微步在线识别
https://s.threatbook.com/report/file/0b41f69e6564b9c89b1b344744c5b06eb4adc0e584028909286d2b936e1afed5?sign=history&env=win7_sp1_enx86_office2013
![64f584e77a05bed722df2467f4acaaf](https://user-images.githubusercontent.com/6202489/211479496-d92b27e9-895b-4884-a6ef-f84a32fd57c5.png)

**Comment by xz-zone** [comment]
已删除
